### ISSUE TITLE
USER STORY: Submit my opinion via poll

### ISSUE THREAD

**Issue by MBilalQureshi** [MBilalQureshi/my-first-agile-project#3]
In order to **provide my opinion related running topics or event** as a **user**, I can **select and submit answer from poll**
## Acceptance Criteria
* The options are provided as checkboxes
* The Submit button should be below the checkboxes
* Only one check box can be selected at a time
# Tasks
- [ ] Create new fields in the model to track the username
- [ ] Update controller function
- [ ] Update test scipts
- [ ] Test functionality
